#https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    # err113 will fail because dynamic errors are defined in several places.
    #- err113
    # ireturn will fail because all pkg clients return interfaces.
    #- ireturn
    - gosec
    - errcheck
    - nilnil
    - nilerr
    - staticcheck