name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:  ["windows-latest", "ubuntu-latest", "macOS-latest"]
        go:  ["1.19.x", "1.20.x", "1.21.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Verify Modules
        run: go mod verify
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.54
      - name: Test
        run: go test ./... -race -vet=off
